version: '3.5'
services:
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: brain
      MONGO_INITDB_ROOT_PASSWORD: brain
    volumes:
      - mongodb_volume:/data/db
  rabbitmq:
    image: rabbitmq:management
    ports:
      - 5672:5672
      - 15672:15672
  server:
    image: brain:latest
    build: .
    ports:
      - 8000:8000
    command: ./wait-for.sh rabbitmq:5672 -- python -m brain.server --queue rabbitmq://rabbitmq:5672 --host 0.0.0.0 --port 8000
    depends_on:
      - rabbitmq
  saver:
    image: brain:latest
    command: ./wait-for.sh mongodb:27017 -- ./wait-for.sh rabbitmq:5672 -- python -m brain.saver run-saver --queue rabbitmq://rabbitmq:5672 --database mongodb://brain:brain@mongodb:27017
    depends_on:
      - server
      - rabbitmq
      - mongodb
  api:
    image: brain:latest
    ports:
    - 5000:5000
    command: ./wait-for.sh mongodb:27017 -- python -m brain.api --host 0.0.0.0 --port 5000 --database mongodb://brain:brain@mongodb:27017
    depends_on:
      - server
      - mongodb
  parser_user:
    image: brain:latest
    command: ./wait-for.sh rabbitmq:5672 -- python -m brain.parser run-parser user mongodb://brain:brain@mongodb:27017
    depends_on:
      - server
      - rabbitmq
  parser_pose:
    image: brain:latest
    command: ./wait-for.sh rabbitmq:5672 -- python -m brain.parser run-parser pose mongodb://brain:brain@mongodb:27017
    depends_on:
      - server
      - rabbitmq
  parser_feelings:
    image: brain:latest
    command: ./wait-for.sh rabbitmq:5672 -- python -m brain.parser run-parser feelings mongodb://brain:brain@mongodb:27017
    depends_on:
      - server
      - rabbitmq

volumes:
  mongodb_volume:
